### ISSUE TITLE
fails to contact wiki due to socks proxy assumption in fetch_cache.py

### ISSUE THREAD

**Issue by dehylton** [nigelm/moin2gitwiki#2]
Docs say that proxy settings default to empty, but due to this block:

        try:
            response = requests.get( 
                url,
                proxies=dict(
                    http="socks5h://localhost:5555",
                    https="socks5h://localhost:5555",
                ),
            )   
            content = response.text
        except OSError:
            self.ctx.logger.warning(f"No response to {url}")
            content = ""

Every fetch attempt fails with "No response to {url}" due to assumed proxy on localhost ... removing the proxies=dict(...) assignment﻿ results in successful page fetch.

**Comment by nigelm** [comment]
That was best described as a bit stupid!  Fixing...
