### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by elsiehupp** [nigelm/moin2gitwiki#5]
I would like to make use of part of this in a derivative project, but doing so is prohibitive without an explicit license to work with.

Could you add an explicit license to this project?

GitHub has help articles for doing so here:

* [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
* [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

And you can then [add the license to your `pyproject.toml`](https://python-poetry.org/docs/pyproject/#license) so it will show up on PyPI.

There are other conventions for including license information in repositories and Python projects (such as [SPDX identifiers](https://spdx.org/licenses/) in source code files), but these are the main ones.

Also worth noting is that the preference for licenses for Python modules seems to be split between A/GPL and MIT/BSD, which is to say that no one seems to like the LGPL when it comes to Python. (I don't have a strong preference here, but I've run into this being a contentious issue elsewhere.)

**Comment by nigelm** [comment]
License has now been added - MIT - knock yourself out :-)

**Comment by elsiehupp** [comment]
Thanks!

**Comment by elsiehupp** [comment]
FYI while I am looking to use this for a somewhat tangential purpose (mirroring a wiki page on GitHub as a README), I'm also a maintainer at [mediawiki-client-tools](https://github.com/orgs/mediawiki-client-tools). (I'm not particularly active in the development; I just took some initiative a while back and accidentally ended up managing the GitHub.)

I saw that you added a note about moin2gitwiki not being actively maintained, and, considering the fact that it serves a related purpose to mediawiki-client-tools, one or more people there may be interested in helping maintain this project, too. [(I just posted about it over there.)](https://github.com/orgs/mediawiki-client-tools/discussions/129)
